name: ci

on:
  push:
    branches:
      - 'test-ci'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: set up qemu
        uses: docker/setup-qemu-action@v2

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: login to github packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: extract docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: build and push
        uses: docker/build-push-action@v3
        with:
          cache-from: type=registry,ref=${{ github.repository }}:${{ github.ref }}-buildcache
          cache-to: type=registry,ref=${{ github.repository }}:${{ github.ref }}-buildcache,mode=max
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}